INSERT INTO `permiso` (`id_permiso`, `nombre_permiso`, `descripcion`) VALUES

/* RH */

-- Medicos --
('1', 'Crear Medicos', 'Permite registrar los datos de los medicos.'),
('2', 'Editar Medicos', 'Permite modificar los datos de los medicos.'),
('3', 'Ver Medicos', 'Permite ver los datos de los medicos'),
('4', 'Desactivar Medicos', 'Permite desactivar los datos de los medicos'),
('5', 'Reactivar Medicos', 'Permite reactivar los datos de los medicos'),
('6', 'Eliminar Medicos', 'Permite eliminar los datos de los medicos'),
-- Areas -
('7', 'Crear Areas', 'Permite registrar las areas de los medicos.'),
('8', 'Editar Areas', 'Permite modificar las areas de los medicos.'),
('9', 'Ver Areas', 'Permite ver los datos de las areas de los medicos'),
('10', 'Desactivar Areas', 'Permite desactivar los areas de los medicos'),
('11', 'Reactivar Areas', 'Permite reactivar los areas de los medicos'),
('12', 'Eliminar Areas', 'Permite eliminar los areas de los medicos'),
-- Especialidades --
('13', 'Crear Especialidades', 'Permite registrar las especialidades de los medicos.'),
('14', 'Editar Especialidades', 'Permite modificar las especialidades de los medicos.'),
('15', 'Ver Especialidades', 'Permite Ver los datos de las especialidades de los medicos'),
('16', 'Desactivar Especialidades', 'Permite desactivar las especialidades de los medicos'),
('17', 'Reactivar Especialidades', 'Permite reactivar las especialidades de los medicos'),
('18', 'Eliminar Especialidades', 'Permite eliminar las especialidades de los medicos'),

/* Administrador (Solamente) */

-- Usuarios
('19', 'Crear Usuarios', 'Permite crear y registrar nuevos usuarios en el sistema.'),
('20', 'Editar Usuarios', 'Permite modificar datos, roles y permisos de cualquier usuario.'),
('21', 'Ver Usuarios', 'Permite ver los usuarios existentes'),
('22', 'Desactivar Usuarios', 'Permite desactivar cuentas de usuario.'),
('23', 'Reactivar', 'Permite reactivar cuentas de usuario.'),
('24', 'Eliminar Usuarios', 'Permite eliminar cuentas de usuario.'),
-- Roles --
('25', 'Crear Roles', 'Permite crear y registrar nuevos roles y sus permisos en el sistema.'),
('26', 'Editar Roles', 'Permite modificar los roles y sus permisos en el sistema.'),
('27', 'Ver Roles', 'Permite ver los roles de usuario'),
('28', 'Desactivar Roles', 'Permite desactivar los roles de usuario.'),
('29', 'Reactivar Roles', 'Permite reactivar los roles de usuario.'),
('30', 'Eliminar Roles', 'Permite eliminar los roles de usuario.'),
-- Permisos --
('31', 'Crear Permisos', 'Permite crear y registrar nuevos permisos y sus permisos en el sistema.'),
('32', 'Editar Permisos', 'Permite modificar los permisos y sus permisos en el sistema .'),
('33', 'Ver Permisos', 'Permite Ver los permisos de usuario'),
('34', 'Desactivar Permisos', 'Permite desactivar los permisos de usuario.'),
('35', 'Reactivar Permisos', 'Permite reactivar los permisos de usuario.'),
('36', 'Eliminar Permisos', 'Permite eliminar los permisos de usuario.'),

/* Medicos */

-- Pacientes --
('37', 'Crear Pacientes', 'Permite crear nuevos registros demograficos de pacientes.'),
('38', 'Editar Pacientes', 'Permite modificar datos personales (telofono, direccion, etc.) del paciente.'),
('39', 'Ver Pacientes', 'Permite acceder al listado y perfil demograficos del paciente.'),
('40', 'Desactivar Pacientes', 'Permite desactivar datos personales (telofono, direccion, etc.) del paciente.'),
('41', 'Reactivar Pacientes', 'Permite reactivar datos personales (telofono, direccion, etc.) del paciente.'),
('42', 'Eliminar Pacientes', 'Permite eliminar datos personales (telofono, direccion, etc.) del paciente.'),
-- Pacientes Menores de Edad --
('43', 'Crear Pacientes Menores de Edad', 'Permite crear nuevos registros demograficos de pacientes menores de edad.'),
('44', 'Editar Pacientes Menores de Edad', 'Permite modificar datos personales (telofono, direccion, etc.) de pacientes menores de edad.'),
('45', 'Ver Pacientes Menores de Edad', 'Permite acceder al listado y perfil demograficos de pacientes menores de edad.'),
('46', 'Desactivar Pacientes Menores de Edad', 'Permite desactivar datos personales (telofono, direccion, etc.) de pacientes menores de edad.'),
('47', 'Reactivar Pacientes Menores de Edad', 'Permite reactivar datos personales (telofono, direccion, etc.) de pacientes menores de edad.'),
('48', 'Eliminar Pacientes Menores de Edad', 'Permite eliminar datos personales (telofono, direccion, etc.) de pacientes menores de edad.'),
-- Representantes --
('49', 'Crear Representantes', 'Permite registrar los datos del representante de un paciente menor.'),
('50', 'Editar Representantes', 'Permite modificar los datos del representante de un paciente menor.'),
('51', 'Ver Representantes', 'Permite Ver los datos de los representantes'),
('52', 'Desactivar Representantes', 'Permite desactivar los datos del representante de un paciente menor.'),
('53', 'Reactivar Representantes', 'Permite reactivar los datos del representante de un paciente menor.'),
('54', 'Eliminar Representantes', 'Permite eliminar los datos del representante de un paciente menor.'),
-- Antecedentes e Historial Medico --
('55', 'Crear Antecedentes', 'Permite regitrar los campos de antecedentes del paciente (Familiares, Estilo de Vida, etc.)'),
('56', 'Editar Antecedentes', 'Permite modificar los campos de antecedentes del paciente (Familiares, Estilo de Vida, etc.)'),
('57', 'Ver Historial Clinico', 'Permite acceder a la pestaña de Historial Clinico y antecedentes.'),
('58', 'Desactivar Historial Clinico', 'Permite desactivar el historial clinico y sus antecedentes.'),
('59', 'Reactivar Historial Clinico', 'Permite reactivar el historial clinico y sus antecedentes.'),
('60', 'Eliminar Historial Clinico', 'Permite eliminar el historial clinico y sus antecedentes.'),
-- Patologias --
('61', 'Crear Patologias', 'Permite registrar patologias.'),
('62', 'Editar Patologias', 'Permite modificar patologias existentes.'),
('63', 'Ver Patologias', 'Permite Ver las patologias'),
('64', 'Desactivar Patologias', 'Permite desactivar patologias existentes'),
('65', 'Reactivar Patologias', 'Permite reactivar patologias existentes'),
('66', 'Eliminar Patologias', 'Permite eliminar patologias existentes'),
-- Sintomas --
('67', 'Crear Sintomas', 'Permite registrar sintomas.'),
('68', 'Editar Sintomas', 'Permite modificar sintomas existentes.'),
('69', 'Ver Sintomas', 'Permite Ver los sintomas'),
('70', 'Desactivar Sintomas', 'Permite desactivar sintomas existentes'),
('71', 'Reactivar Sintomas', 'Permite reactivar sintomas existentes'),
('72', 'Eliminar Sintomas', 'Permite eliminar sintomas existentes'),
-- Alergias --
('73', 'Crear Alergias', 'Permite registrar alergias existentes.'),
('74', 'Editar Alergias', 'Permite modificar alergias existentes.'),
('75', 'Ver Alergias', 'Permite Ver las alergias'),
('76', 'Desactivar Alergias', 'Permite desactivar alergias existentes'),
('77', 'Reactivar Alergias', 'Permite reactivar alergias existentes'),
('78', 'Eliminar Alergias', 'Permite eliminar alergias existentes'),
-- Consultas --
('79', 'Crear Consultas', 'Permite iniciar y guardar una nueva consulta modica.'),
('80', 'Editar Consultas', 'Permite modificar datos de una consulta ya guardada (usualmente restringido).'),
('81', 'Ver Consultas', 'Permite ver el listado de consultas y acceder al detalle de consultas historicas.'),
('82', 'Desactivar Consultas', 'Permite desactivar datos de una consulta.'),
('83', 'Reactivar Consultas', 'Permite reactivar datos de una consulta.'),
('84', 'Eliminar Consultas', 'Permite eliminar datos de una consulta.'),
-- Citas --
('85', 'Crear Citas', 'Permite iniciar y guardar una nueva cita modica.'),
('86', 'Editar Citas', 'Permite modificar datos de una cita medica.'),
('87', 'Ver Citas', 'Permite ver el listado de citas.'),
('88', 'Desactivar Citas', 'Permite desactivar datos de una cita medica.'),
('89', 'Reactivar Citas', 'Permite reactivar datos de una cita medica.'),
('90', 'Eliminar Citas', 'Permite eliminar datos de una cita medica.'),

/* Farmaceutico */

-- Inventario --
('91', 'Generar Entradas de Inventario', 'Permite generar entradas y salidas del inventario'),
('92', 'Generar Salidas de Inventario', 'Permite generar entradas y salidas del inventario'),
('93', 'Ajustar Stock de Medicamentos', 'Permite modificar el stock minimo y maximo de un medicamento'),
('94', 'Editar Movimientos de Inventario', 'Permite editar entradas y salidas del inventario.'),
('95', 'Ver Inventario', 'Permite ver el listado y stock actual del inventario.'),
('96', 'Desactivar Movimientos de Inventario', 'Permite desactivar movimientos en el inventario.'),
('97', 'Reactivar Movimientos de Inventario', 'Permite reactivar movimientos en el inventario.'),
('98', 'Eliminar Movimientos de Inventario', 'Permite eliminar movimientos en el inventario.'),
-- Medicamentos --
('99', 'Crear Medicamentos', 'Permite registrar nuevos medicamentos en el catologo.'),
('100', 'Editar Medicamentos', 'Permite modificar la informacion de medicamentos existentes.'),
('101', 'Ver Medicamentos', 'Permite ver el listado de medicamentos existentes.'),
('102', 'Desactivar Medicamentos', 'Permite desactivar la informacion de medicamentos existentes.'),
('103', 'Reactivar Medicamentos', 'Permite reactivar la informacion de medicamentos existentes.'),
('104', 'Eliminar Medicamentos', 'Permite eliminar la informacion de medicamentos existentes.'),
-- Lotes --
('105', 'Crear Lotes', 'Permite registrar nuevos lotes en el catologo.'),
('106', 'Editar Lotes', 'Permite modificar la informacion de los lotes existentes.'),
('107', 'Ver Lotes', 'Permite ver el listado de los lotes existentes.'),
('108', 'Desactivar Lotes', 'Permite desactivar la informacion de los lotes existentes.'),
('109', 'Reactivar Lotes', 'Permite reactivar la informacion de los lotes existentes.'),
('110', 'Eliminar Lotes', 'Permite eliminar la informacion de los lotes existentes.'),

/* Barra de navegacion */

('111', 'Gestionar Consultas','Permite administrar las consultass.'),
('112', 'Gestionar Citas','Permite administrar las citas.'),
('113', 'Gestionar Pacientes','Permite administrar los datos de los pacientes.'),
('114', 'Gestionar Salud','Permite administrar los datos de las patologias, alergias, etc.'),
('115', 'Gestionar RH', 'Permite administrar las areas, empleados, etc.'),
('116', 'Gestionar Farmacia', 'Permite ver el panel completo del inventario.'),
('117', 'Gestionar Configuraciones','Permite administrar las configuraciones.'),

/* Reportes */

('118', 'Generar Reportes de Pacientes', 'Permite crear reportes de pacientes.'),
('119', 'Generar Reportes de Pacientes Menores de Edad', 'Permite crear reportes de pacientes menores de edad.'),
('121', 'Generar Reportes de Citas', 'Permite crear reportes de citas.'),
('122', 'Generar Recipe Medico', 'Permite crear el recipe medico de un paciente.'),
('123', 'Generar Comprobante de Cita', 'Permite crear el comprobante de una cita de un paciente.'),
('124', 'Generar Reportes de Consultas', 'Permite crear reportes de consultas.'),
('125', 'Generar Reportes de Representantes', 'Permite crear reportes de representantes.'),
('126', 'Generar Reportes de Patologias', 'Permite crear reportes de patologias.'),
('127', 'Generar Reportes de Alergias', 'Permite crear reportes de alergias.'),
('128', 'Generar Reportes de Sintomas', 'Permite crear reportes de sintomas.'),
('129', 'Generar Reportes de Medicos', 'Permite crear reportes de medicos.'),
('130', 'Generar Reportes de Areas', 'Permite crear reportes de areas.'),
('131', 'Generar Reportes de Especialidades', 'Permite crear reportes de especialidades.'),
('132', 'Generar Reportes de Inventario', 'Permite crear reportes de inventario.'),
('133', 'Generar Reportes de Medicamentos', 'Permite crear reportes de medicamentos.'),
('134', 'Generar Reportes de Lotes', 'Permite crear reportes de lotes.'),

/* Dashboard */

('135', 'Ver panel de administrador', 'Permite visualizar las informaciones principales en el dasboard.'),
('136', 'Ver panel de medicos', 'Permite visualizar las informaciones principales en el dasboard.'),
('137', 'Ver panel de farmaceutico', 'Permite visualizar las informaciones principales en el dasboard.'),
('138', 'Ver panel de recepcionista', 'Permite visualizar las informaciones principales en el dasboard.'),
('139', 'Ver panel de recursos humanos', 'Permite visualizar las informaciones principales en el dasboard.'),
('140', 'Ver panel de visitante', 'Permite visualizar las informaciones principales en el dasboard.'),

/* Notificaciones */

('141', 'Ver notificaciones de citas', 'Permite ver las notificaciones relacionadas con las citas.'),
('142', 'Ver notificaciones de inventario', 'Permite ver las notificaciones relacionadas con el inventario.'),
('143', 'Ver notificaciones de lotes', 'Permite ver las notificaciones relacionadas con el inventario.'),

/* Papelera */

('144', 'Ver papelera de pacientes', 'Permite administrar la papelera relacionada con los pacientes.'),
('145', 'Ver papelera de pacientes menores de edad', 'Permite administrar la papelera relacionada con los pacientes menores de edad.'),
('146', 'Ver papelera de representantes', 'Permite administrar la papelera relacionada con los representantantes.'),
('147', 'Ver papelera de citas', 'Permite administrar la papelera relacionada con las citas.'),
('148', 'Ver papelera de consultas', 'Permite administrar la papelera relacionada con las consultas.'),
('149', 'Ver papelera de patologias', 'Permite administrar la papelera relacionada con las patologias.'),
('150', 'Ver papelera de alergias', 'Permite administrar la papelera relacionada con las alergias.'),
('151', 'Ver papelera de sintomas', 'Permite administrar la papelera relacionada con los sintomas.'),
('152', 'Ver papelera de inventario', 'Permite administrar la papelera relacionada con el inventario.'),
('153', 'Ver papelera de medicamentos', 'Permite administrar la papelera relacionada con los medicamentos.'),
('154', 'Ver papelera de lotes', 'Permite administrar la papelera relacionada con los lotes.'),
('155', 'Ver papelera de medicos', 'Permite administrar la papelera relacionada con los medicos.'),
('156', 'Ver papelera de areas', 'Permite administrar la papelera relacionada con las areas.'),
('157', 'Ver papelera de especialidades', 'Permite ve las papelera relacionada con las especialidades.'),
('158', 'Ver papelera de usuarios', 'Permite administrar la papelera relacionada con los usuarios.'),
('159', 'Ver papelera de roles', 'Permite administrar la papelera relacionada con los roles.'),
('160', 'Ver papelera de permisos', 'Permite administrar la papelera relacionada con los permisos.'),

/* Columna de acciones (CRUD) */

('161', 'Gestionar acciones de pacientes', 'Permite realizar acciones en el modulo de pacientes (editar, eliminar, etc).'),
('162', 'Gestionar acciones de pacientes menores de edad', 'Permite realizar acciones en el modulo de pacientes menores de edad (editar, eliminar, etc).'),
('163', 'Gestionar acciones de representantes', 'Permite realizar acciones en el modulo de representantes (editar, eliminar, etc).'),
('164', 'Gestionar acciones de citas', 'Permite realizar acciones en el modulo de citas (editar, eliminar, etc).'),
('165', 'Gestionar acciones de consultas', 'Permite realizar acciones en el modulo de consultas (editar, eliminar, etc).'),
('166', 'Gestionar acciones de patologias', 'Permite realizar acciones en el modulo de patologias (editar, eliminar, etc).'),
('167', 'Gestionar acciones de alergias', 'Permite realizar acciones en el modulo de alergias (editar, eliminar, etc).'),
('168', 'Gestionar acciones de sintomas', 'Permite realizar acciones en el modulo de sintomas (editar, eliminar, etc).'),
('169', 'Gestionar acciones de inventario', 'Permite realizar acciones en el modulo de inventario (editar, eliminar, etc).'),
('170', 'Gestionar acciones de medicamentos', 'Permite realizar acciones en el modulo de medicamentos (editar, eliminar, etc).'),
('171', 'Gestionar acciones de lotes', 'Permite realizar acciones en el modulo de lotes (editar, eliminar, etc).'),
('172', 'Gestionar acciones de medicos', 'Permite realizar acciones en el modulo de medicos (editar, eliminar, etc).'),
('173', 'Gestionar acciones de areas', 'Permite realizar acciones en el modulo de areas (editar, eliminar, etc).'),
('174', 'Gestionar acciones de especialidades', 'Permite realizar acciones en el modulo de especialidades (editar, eliminar, etc).'),
('175', 'Gestionar acciones de usuarios', 'Permite realizar acciones en el modulo de usuarios (editar, eliminar, etc).'),
('176', 'Gestionar acciones de roles', 'Permite realizar acciones en el modulo de roles (editar, eliminar, etc).'),
('177', 'Gestionar acciones de permisos', 'Permite realizar acciones en el modulo de permisos (editar, eliminar, etc).');

/* Consultas SQL para Insertar */

-- Administrador --

INSERT INTO `rol_permiso` (`Id_rol_permiso`, `Id_rol`, `Id_permiso`) VALUES

('1','1','1'),
('2','1','2'),
('3','1','3'),
('4','1','4'),
('5','1','5'),
('6','1','6'),
('7','1','7'),
('8','1','8'),
('9','1','9'),
('10','1','10'),
('11','1','11'),
('12','1','12'),
('13','1','13'),
('14','1','14'),
('15','1','15'),
('16','1','16'),
('17','1','17'),
('18','1','18'),
('19','1','19'),
('20','1','20'),
('21','1','21'),
('22','1','22'),
('23','1','23'),
('24','1','24'),
('25','1','25'),
('26','1','26'),
('27','1','27'),
('28','1','28'),
('29','1','29'),
('30','1','30'),
('31','1','31'),
('32','1','32'),
('33','1','33'),
('34','1','34'),
('35','1','35'),
('36','1','36'),
('37','1','37'),
('38','1','38'),
('39','1','39'),
('40','1','40'),
('41','1','41'),
('42','1','42'),
('43','1','43'),
('44','1','44'),
('45','1','45'),
('46','1','46'),
('47','1','47'),
('48','1','48'),
('49','1','49'),
('50','1','50'),
('51','1','51'),
('52','1','52'),
('53','1','53'),
('54','1','54'),
('55','1','55'),
('56','1','56'),
('57','1','57'),
('58','1','58'),
('59','1','59'),
('60','1','60'),
('61','1','61'),
('62','1','62'),
('63','1','63'),
('64','1','64'),
('65','1','65'),
('66','1','66'),
('67','1','67'),
('68','1','68'),
('69','1','69'),
('70','1','70'),
('71','1','71'),
('72','1','72'),
('73','1','73'),
('74','1','74'),
('75','1','75'),
('76','1','76'),
('77','1','77'),
('78','1','78'),
('79','1','79'),
('80','1','80'),
('81','1','81'),
('82','1','82'),
('83','1','83'),
('84','1','84'),
('85','1','85'),
('86','1','86'),
('87','1','87'),
('88','1','88'),
('89','1','89'),
('90','1','90'),
('91','1','91'),
('92','1','92'),
('93','1','93'),
('94','1','94'),
('95','1','95'),
('96','1','96'),
('97','1','97'),
('98','1','98'),
('99','1','99'),
('100','1','100'),
('101','1','101'),
('102','1','102'),
('103','1','103'),
('104','1','104'),
('105','1','105'),
('106','1','106'),
('107','1','107'),
('108','1','108'),
('109','1','109'),
('110','1','110'),
('111','1','111'),
('112','1','112'),
('113','1','113'),
('114','1','114'),
('115','1','115'),
('116','1','116'),
('117','1','117'),
('118','1','118'),
('119','1','119'),
('120','1','120'),
('121','1','121'),
('122','1','122'),
('123','1','123'),
('124','1','124'),
('125','1','125'),
('126','1','126'),
('127','1','127'),
('128','1','128'),
('129','1','129'),
('130','1','130'),
('131','1','131'),
('132','1','132'),
('133','1','133'),
('134','1','134'),
('135','1','135'),
('136','1','141'),
('137','1','142'),
('138','1','143'),
('139','1','144'),
('140','1','145'),
('141','1','146'),
('142','1','147'),
('143','1','148'),
('144','1','149'),
('145','1','150'),
('146','1','151'),
('147','1','152'),
('148','1','153'),
('149','1','154'),
('150','1','155'),
('151','1','156'),
('152','1','157'),
('153','1','158'),
('154','1','159'),
('155','1','160'),
('156','1','161'),
('157','1','162'),
('158','1','163'),
('159','1','164'),
('160','1','165'),
('161','1','166'),
('162','1','167'),
('163','1','168'),
('164','1','169'),
('165','1','170'),
('166','1','171'),
('167','1','172'),
('168','1','173'),
('169','1','174'),
('170','1','175'),
('171','1','176'),
('172','1','177');

-- Visitante --

INSERT INTO `rol_permiso`(`Id_rol_permiso`, `Id_rol`, `Id_permiso`) VALUES

('173','2','3'),
('174','2','9'),
('175','2','15'),
('176','2','39'),
('177','2','45'),
('178','2','51'),
('179','2','53'),
('180','2','63'),
('181','2','69'),
('182','2','75'),
('183','2','81'),
('184','2','87'),
('185','2','101'),
('186','2','107'),
('187','2','111'),
('188','2','112'),
('189','2','113'),
('190','2','114'),
('191','2','115'),
('192','2','116'),
('193','2','161'),
('194','2','162'),
('195','2','164'),
('196','2','165'),
('197','2','172'),
('198','2','140');

-- Farmaceutico --

INSERT INTO `rol_permiso` (`Id_rol_permiso`, `Id_rol`, `Id_permiso`) VALUES

('199','6','91'),
('200','6','92'),
('201','6','93'),
('202','6','94'),
('203','6','95'),
('204','6','96'),
('205','6','97'),
('206','6','98'),
('207','6','99'),
('208','6','100'),
('209','6','101'),
('210','6','102'),
('211','6','103'),
('212','6','104'),
('213','6','105'),
('214','6','106'),
('215','6','107'),
('216','6','108'),
('217','6','109'),
('218','6','110'),
('219','6','116'),
('220','6','132'),
('221','6','133'),
('222','6','134'),
('223','6','142'),
('224','6','143'),
('225','6','169'),
('226','6','170'),
('227','6','171'),
('228','6','137');

-- Medicos --

INSERT INTO `rol_permiso` (`Id_rol_permiso`, `Id_rol`, `Id_permiso`) VALUES

('230','7','37'),
('231','7','38'),
('232','7','39'),
('233','7','43'),
('234','7','44'),
('235','7','45'),
('236','7','55'),
('237','7','56'),
('238','7','57'),
('239','7','61'),
('240','7','62'),
('241','7','63'),
('242','7','67'),
('243','7','68'),
('244','7','69'),
('245','7','73'),
('246','7','74'),
('247','7','75'),
('248','7','79'),
('249','7','80'),
('250','7','81'),
('251','7','85'),
('252','7','86'),
('253','7','87'),
('254','7','111'),
('255','7','112'),
('256','7','113'),
('257','7','114'),
('258','7','118'),
('259','7','119'),
('260','7','120'),
('261','7','121'),
('262','7','122'),
('263','7','123'),
('264','7','124'),
('265','7','125'),
('266','7','126'),
('267','7','127'),
('268','7','128'),
('269','7','136'),
('270','7','141'),
('271','7','161'),
('272','7','162'),
('273','7','163'),
('274','7','164'),
('275','7','165'),
('276','7','166'),
('277','7','167'),
('278','7','168');

-- Administrador - RH --

INSERT INTO `rol_permiso` (`Id_rol_permiso`, `Id_rol`, `Id_permiso`) VALUES

('279','8','1'),
('280','8','2'),
('281','8','3'),
('282','8','4'),
('283','8','7'),
('284','8','8'),
('285','8','9'),
('286','8','10'),
('287','8','13'),
('288','8','14'),
('289','8','15'),
('290','8','16'),
('291','8','115'),
('292','8','129'),
('293','8','130'),
('294','8','131'),
('295','8','139'),
('296','8','172'),
('297','8','173'),
('298','8','174');



